// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ7OI-MFAlCUD3WG7wXjYF9SYD5sFchWw',
    appId: '1:987595589557:web:c2f7e7d7cdec5c73a37bfc',
    messagingSenderId: '987595589557',
    projectId: 'mindprint-db',
    authDomain: 'mindprint-db.firebaseapp.com',
    storageBucket: 'mindprint-db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlt2qjlks7Yz9QPgx3WaZjTMmlKjx_tlo',
    appId: '1:987595589557:android:21f7da80a56bfb7ca37bfc',
    messagingSenderId: '987595589557',
    projectId: 'mindprint-db',
    storageBucket: 'mindprint-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFGgfbEq409tSP8UAgHfzBvQiYyHuyW3c',
    appId: '1:987595589557:ios:1469061a6540ecfea37bfc',
    messagingSenderId: '987595589557',
    projectId: 'mindprint-db',
    storageBucket: 'mindprint-db.firebasestorage.app',
    iosBundleId: 'com.example.mindPrint',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ7OI-MFAlCUD3WG7wXjYF9SYD5sFchWw',
    appId: '1:987595589557:web:81621a5d452367eaa37bfc',
    messagingSenderId: '987595589557',
    projectId: 'mindprint-db',
    authDomain: 'mindprint-db.firebaseapp.com',
    storageBucket: 'mindprint-db.firebasestorage.app',
  );
}
