name: Release APK

on:
  push:
    branches:
      - release/development
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build and Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Create .env file
        run: |
          if [ -z "${{ secrets.DOTENV_FILE }}" ]; then
            echo "No DOTENV_FILE secret found. Creating an empty .env file."
            touch .env
          else
            echo "${{ secrets.DOTENV_FILE }}" > .env
          fi

      - name: Get Dependencies
        run: flutter pub get

      - name: Build APKs
        run: |
          # Build split APKs for smaller sizes
          flutter build apk --release --split-per-abi
          # Build one universal APK for easy sharing
          flutter build apk --release

      - name: Get SHA Fingerprints
        run: |
          echo "### SHA-1 and SHA-256 Fingerprints for Firebase ###"
          keytool -list -v -keystore ~/.android/debug.keystore -alias androiddebugkey -storepass android -keypass android | grep -E "SHA1|SHA256"
          echo "#################################################"

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
            build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            build/app/outputs/flutter-apk/app-x86_64-release.apk
            build/app/outputs/flutter-apk/app-release.apk
          name: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || 'Latest Main Build' }}
          tag_name: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || 'latest' }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
